#pragma once

class BaseElement;
class Expression;
class NumberExpression;
class AddExpression;
class SubstractExpression;
class MulExpression;
class DivExpression;
class IdentExpression;
class Statement;
class PrintStatement;
class VarDecl;
class Assignment;
class AssignmentList;
class ScopeAssignmentList;
class Program;
class ParamList;
class Function;
class FunctionCallExpression;
class FunctionList;
class ParamValueList;
class ReturnStatement;
